[package]
name = "spellcast-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trees = "0.4.2"
postgres = "0.19.2"
log= "0.4.14"
env_logger= "0.9.0"
